### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by iHamzaaK** [StraaS/StraaS-iOS-sdk#163]
Hello,

I am trying to find registration link for straas sdk but couldnt find one?

**Comment by iHamzaaK** [comment]
@allenlinli

**Comment by PrashantKT** [comment]
@iHamzaaK  I am also not able to find it.

**Comment by iHamzaaK** [comment]
@PrashantKT Any work around of this?

**Comment by jasonchuang** [comment]
Hi, please try to contact our BD via email contact@straas.io or web https://straas.io/contact/ for further registration information, thx

**Comment by iHamzaaK** [comment]
@jasonchuang  I have been emailing on the above address for quite some time and they are not responding.

**Comment by allenlinli** [comment]
Hi @iHamzaaK @PrashantKT  thank you for contacting us, sorry I missed the message here for a while.
We've reply to your message on contact@straas.io. Please let us know if you need more help, thanks.
