### ISSUE TITLE
xcode build fail ,  [TTTAttributedLabel new]  NS_UNAVAILABLE

### ISSUE THREAD

**Issue by zeqinjie** [Straas/Straas-iOS-sdk#229]
Welcome to StraaS and thanks for submitting an issue!

Please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * Contact our [tech support](https://straas.io/contact/) for further service and assistance.

### Step 2: Describe your environment

  * Objective C or Swift: __obj__
  * iOS version: __ 0.61.0___
  * iOS SDK version: __ 0.61.0___
  * Use StraaS UI or not: ____true_
  * Cocoapods version: __1.10.1__
  * Xcode version: __12.5__
  
  
### Step 3: Describe the problem:
 xcode build fail 

reason:
@interface TTTAttributedLabel : UILabel <TTTAttributedLabel, UIGestureRecognizerDelegate>
/**
 * The designated initializers are @c initWithFrame: and @c initWithCoder:.
 * init will not properly initialize many required properties and other configuration.
 */
- (instancetype) init NS_UNAVAILABLE;

**Comment by dminoror** [comment]
Hi, thanks for the report!

Change **[TTTAttributedLabel new]** to **[[TTTAttributedLabel alloc] initWithFrame:CGRectZero]** should be fine.

This error will fix in next version.
